# Generated by Django 5.2.7 on 2025-10-19 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('products', '0004_remove_trend_item_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.farmersubmission'),
        ),
    ]
