# Generated by Django 5.2.7 on 2025-10-19 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_trend_item_remove_order_product_and_more'),
        ('transactions', '0002_contactrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactrequest',
            name='is_viewed',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='product',
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='submission',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='products.farmersubmission'),
            preserve_default=False,
        ),
    ]
