# Generated by Django 5.2.7 on 2025-10-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_message_options_remove_message_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_by_receiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by_sender',
            field=models.BooleanField(default=False),
        ),
    ]
