# Generated by Django 5.2.7 on 2025-10-19 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_marketitem_farmersubmission_trend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trend',
            name='item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='MarketItem',
        ),
        migrations.DeleteModel(
            name='Trend',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
