# Generated by Django 5.2.7 on 2025-10-24 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubmission',
            name='status',
        ),
    ]
