# Generated by Django 5.2.7 on 2025-10-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_productsubmission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubmission',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
